class MarketMapper:
    """Maps cities to major metropolitan markets for job clustering"""
    
    def __init__(self):
        # Comprehensive market lookup from Colab version
        self.market_lookup = {
            "acampo, ca": ["Stockton"],
            "ackworth, ia": ["Des Moines"],
            "addison, tx": ["Dallas"],
            "aledo, tx": ["Dallas"],
            "alhambra, ca": ["Inland Empire"],
            "allen, tx": ["Dallas"],
            "allentown, nj": ["Trenton"],
            "allentown, pa": ["Trenton"],
            "altoona, ia": ["Des Moines"],
            "alvin, tx": ["Houston"],
            "ames, ia": ["Des Moines"],
            "amityville, ny": ["Newark"],
            "anaheim, ca": ["Inland Empire"],
            "anahuac, tx": ["Houston"],
            "andover, nj": ["Newark"],
            "angleton, tx": ["Houston"],
            "ankeny, ia": ["Des Moines"],
            "antioch, ca": ["Stockton"],
            "apache junction, az": ["Phoenix"],
            "argyle, tx": ["Dallas"],
            "arlington, tx": ["Dallas"],
            "armonk, ny": ["Newark"],
            "arvada, co": ["Denver"],
            "arverne, ny": ["Newark"],
            "aubrey, tx": ["Dallas"],
            "auburn, ca": ["Sacramento"],
            "audubon, nj": ["Trenton"],
            "audubon, pa": ["Trenton"],
            "aurora, co": ["Denver"],
            "austin, mn": ["Rochester"],
            "avenel, nj": ["Newark"],
            "avondale, az": ["Phoenix"],
            "azusa, ca": ["Inland Empire"],
            "babylon, ny": ["Newark"],
            "bacliff, tx": ["Houston"],
            "balch springs, tx": ["Dallas"],
            "ballico, ca": ["Stockton"],
            "banning, ca": ["Inland Empire"],
            "bardwell, tx": ["Dallas"],
            "bay shore, ny": ["Newark"],
            "bayonne, nj": ["Newark"],
            "baytown, tx": ["Houston"],
            "bayville, nj": ["Trenton"],
            "bayville, ny": ["Newark"],
            "beaumont, ca": ["Inland Empire"],
            "beaverdale, ia": ["Des Moines"],
            "bedford, ny": ["Newark"],
            "bedminster, nj": ["Newark"],
            "bedminster township, pa": ["Trenton"],
            "bell, ca": ["Inland Empire"],
            "bell gardens, ca": ["Inland Empire"],
            "bellaire, tx": ["Houston"],
            "belleville, nj": ["Newark"],
            "bellflower, ca": ["Inland Empire"],
            "bellmawr, nj": ["Trenton"],
            "belmont, ca": ["Bay Area"],
            "benicia, ca": ["Bay Area", "Sacramento"],
            "bensalem, pa": ["Trenton"],
            "berkeley, ca": ["Bay Area"],
            "berlin, nj": ["Trenton"],
            "bernardsville, nj": ["Newark"],
            "bethlehem, pa": ["Trenton"],
            "bethpage, ny": ["Newark"],
            "black canyon city, az": ["Phoenix"],
            "bloomfield, nj": ["Newark"],
            "bloomington, ca": ["Inland Empire"],
            "blue bell, pa": ["Trenton"],
            "bogota, nj": ["Newark"],
            "bondurant, ia": ["Des Moines"],
            "boone, ia": ["Des Moines"],
            "bordentown, nj": ["Trenton"],
            "boulder, co": ["Denver"],
            "boulder city, nv": ["Las Vegas"],
            "brea, ca": ["Inland Empire"],
            "brentwood, ca": ["Stockton"],
            "bridgeport, pa": ["Trenton"],
            "bridgeton, nj": ["Trenton"],
            "bridgewater, nj": ["Newark"],
            "brighton, co": ["Denver"],
            "brisbane, ca": ["Bay Area"],
            "bristol, pa": ["Trenton"],
            "bronx, ny": ["Newark"],
            "brooklyn, ny": ["Newark"],
            "brookshire, tx": ["Houston"],
            "broomfield, co": ["Denver"],
            "buckeye, az": ["Phoenix"],
            "budd lake, nj": ["Newark"],
            "buena park, ca": ["Inland Empire"],
            "burlington, nj": ["Trenton"],
            "burlington township, nj": ["Trenton"],
            "butler, nj": ["Newark"],
            "byron, ca": ["Stockton"],
            "byron, mn": ["Rochester"],
            "caddo mills, tx": ["Dallas"],
            "camden, nj": ["Trenton"],
            "campbell, ca": ["Bay Area"],
            "cannon falls, mn": ["Rochester"],
            "carlisle, ia": ["Des Moines"],
            "carlstadt, nj": ["Newark"],
            "carrollton, tx": ["Dallas"],
            "carteret, nj": ["Newark"],
            "casa grande, az": ["Phoenix"],
            "castle rock, co": ["Denver"],
            "cave creek, az": ["Phoenix"],
            "cedar grove, nj": ["Newark"],
            "cedar hill, tx": ["Dallas"],
            "celeste, tx": ["Dallas"],
            "centennial, co": ["Denver"],
            "ceres, ca": ["Stockton"],
            "cerritos, ca": ["Inland Empire"],
            "chalfont, pa": ["Trenton"],
            "chandler, az": ["Phoenix"],
            "channelview, tx": ["Houston"],
            "chappaqua, ny": ["Newark"],
            "chariton, ia": ["Des Moines"],
            "chatfield, mn": ["Rochester"],
            "cherry hill, nj": ["Trenton"],
            "cherry hill township, nj": ["Trenton"],
            "chester, ia": ["Rochester"],
            "chester, ny": ["Newark"],
            "chester, pa": ["Trenton"],
            "chino, ca": ["Inland Empire"],
            "chino hills, ca": ["Inland Empire"],
            "cinnaminson, nj": ["Trenton"],
            "citrus heights, ca": ["Sacramento"],
            "city of industry, ca": ["Inland Empire"],
            "city of orange, nj": ["Newark"],
            "claremont, mn": ["Rochester"],
            "clements, ca": ["Stockton"],
            "cleveland, tx": ["Houston"],
            "clifton, nj": ["Newark"],
            "clive, ia": ["Des Moines"],
            "clodine, tx": ["Houston"],
            "cold spring, ny": ["Newark"],
            "collingswood, nj": ["Trenton"],
            "collins, ia": ["Des Moines"],
            "colmar, pa": ["Trenton"],
            "colton, ca": ["Inland Empire"],
            "colwyn, pa": ["Trenton"],
            "commack, ny": ["Newark"],
            "commerce, ca": ["Inland Empire"],
            "commerce city, co": ["Denver"],
            "commerce city, co, us": ["Denver"],
            "compton, ca": ["Inland Empire"],
            "concord, ca": ["Bay Area"],
            "conroe, tx": ["Houston"],
            "conshohocken, pa": ["Trenton"],
            "coppell, tx": ["Dallas"],
            "corbin city, nj": ["Trenton"],
            "cornwall, ny": ["Trenton"],
            "corona, ca": ["Inland Empire"],
            "corona, ny": ["Newark"],
            "costa mesa, ca": ["Inland Empire"],
            "cranford, nj": ["Newark"],
            "cresco, ia": ["Rochester"],
            "cresson, tx": ["Dallas"],
            "crestline, ca": ["Inland Empire"],
            "croton-on-hudson, ny": ["Newark"],
            "croydon, pa": ["Trenton"],
            "crystal beach, tx": ["Houston"],
            "crystalaire, ca": ["Inland Empire"],
            "cudahy, ca": ["Inland Empire"],
            "cypress, tx": ["Houston"],
            "dallas, tx": ["Dallas"],
            "dallas, tx, us": ["Dallas"],
            "dallas-fort worth, tx": ["Dallas"],
            "daly city, ca": ["Bay Area"],
            "darby, pa": ["Trenton"],
            "darien, ct": ["Newark"],
            "davis, ca": ["Sacramento", "Stockton"],
            "dayton, nj": ["Newark"],
            "dayton, tx": ["Houston"],
            "deer park, tx": ["Houston"],
            "delhi, ca": ["Stockton"],
            "denton, tx": ["Dallas"],
            "denver, co": ["Denver"],
            "des moines, ia": ["Des Moines"],
            "desoto, tx": ["Dallas"],
            "dickinson, tx": ["Houston"],
            "discovery bay, ca": ["Stockton"],
            "dodge center, mn": ["Rochester"],
            "dover, nj": ["Newark"],
            "downey, ca": ["Inland Empire"],
            "doylestown, pa": ["Trenton"],
            "dufour, ca": ["Sacramento"],
            "dumont, co": ["Denver"],
            "duncanville, tx": ["Dallas"],
            "dunellen, nj": ["Newark"],
            "durand, wi": ["Rochester"],
            "eagleville, pa": ["Trenton"],
            "east brunswick, nj": ["Newark"],
            "east elmhurst, ny": ["Newark"],
            "east hanover, nj": ["Newark"],
            "east northport, ny": ["Newark"],
            "east norwich, ny": ["Newark"],
            "east oakdale, ca": ["Stockton"],
            "east orange, nj": ["Newark"],
            "east stroudsburg, pa": ["Trenton"],
            "east windsor, nj": ["Trenton"],
            "easton, pa": ["Trenton"],
            "eastvale, ca": ["Inland Empire"],
            "eatontown, nj": ["Newark"],
            "eddington, pa": ["Trenton"],
            "edgewood, ny": ["Newark"],
            "edison, nj": ["Newark", "Trenton"],
            "egg harbor township, nj": ["Trenton"],
            "el dorado hills, ca": ["Stockton"],
            "el mirage, az": ["Phoenix"],
            "el monte, ca": ["Inland Empire"],
            "elizabeth, co": ["Denver"],
            "elizabeth, nj": ["Newark"],
            "elk grove, ca": ["Stockton", "Sacramento"],
            "elmer, nj": ["Trenton"],
            "elmont, ny": ["Newark"],
            "elmwood park, nj": ["Newark"],
            "empire, ca": ["Stockton"],
            "englewood, co": ["Denver"],
            "englewood, nj": ["Newark"],
            "ennis, tx": ["Dallas"],
            "enterprise, nv": ["Las Vegas"],
            "escalon, ca": ["Stockton"],
            "essington, pa": ["Trenton"],
            "euless, tx": ["Dallas"],
            "ewing, nj": ["Newark"],
            "ewing township, nj": ["Trenton"],
            "exton, pa": ["Trenton"],
            "eyota, mn": ["Rochester"],
            "fair lawn, nj": ["Newark"],
            "fairfield, ca": ["Bay Area", "Sacramento"],
            "fairfield, nj": ["Newark"],
            "fairless hills, pa": ["Trenton"],
            "fairview, nj": ["Newark"],
            "fallbrook, ca": ["Inland Empire"],
            "far hills, nj": ["Newark"],
            "faribault, mn": ["Rochester"],
            "farmingdale, ny": ["Newark"],
            "farmington, ca": ["Stockton"],
            "feasterville-trevose, pa": ["Trenton"],
            "ferris, tx": ["Dallas"],
            "fieldsboro, nj": ["Trenton"],
            "firestone, co": ["Denver"],
            "flemington, nj": ["Trenton"],
            "florida, ny": ["Trenton", "Newark"],
            "flower mound, tx": ["Dallas"],
            "flushing, ny": ["Newark"],
            "folcroft, pa": ["Trenton"],
            "folsom, ca": ["Sacramento", "Stockton"],
            "fontana, ca": ["Inland Empire"],
            "forest hill, tx": ["Dallas"],
            "forney, tx": ["Dallas"],
            "fort lee, nj": ["Newark"],
            "fort lupton, co": ["Denver"],
            "fort worth, tx": ["Dallas"],
            "fort worth, tx, us": ["Dallas"],
            "fountain valley, ca": ["Inland Empire"],
            "franklin, nj": ["Newark"],
            "franklin square, ny": ["Newark"],
            "franktown, co": ["Denver"],
            "fraser, co": ["Denver"],
            "freehold, nj": ["Newark"],
            "freehold township, nj": ["Newark"],
            "freeport, ny": ["Newark"],
            "fremont, ca": ["Bay Area"],
            "french camp, ca": ["Stockton"],
            "friendswood, tx": ["Houston"],
            "frisco, tx": ["Dallas"],
            "fruitville, pa": ["Trenton"],
            "fullerton, ca": ["Inland Empire"],
            "galena park, tx": ["Houston"],
            "galt, ca": ["Stockton"],
            "galveston, tx": ["Houston"],
            "garden city, ia": ["Des Moines"],
            "garden city, ny": ["Newark"],
            "garden grove, ca": ["Inland Empire"],
            "garland, tx": ["Dallas"],
            "gilbert, az": ["Phoenix"],
            "gilbert, ia": ["Des Moines"],
            "gilbertsville, pa": ["Trenton"],
            "gilcrest, co": ["Denver"],
            "glassboro, nj": ["Trenton"],
            "glen ridge, nj": ["Newark"],
            "glendale, az": ["Phoenix"],
            "glenolden, pa": ["Trenton"],
            "glenside, pa": ["Trenton"],
            "gold canyon, az": ["Phoenix"],
            "golden, co": ["Denver"],
            "goldens bridge, ny": ["Trenton"],
            "goodsprings, nv": ["Las Vegas"],
            "goodyear, az": ["Phoenix"],
            "grand meadow, mn": ["Rochester"],
            "grand prairie, tx": ["Dallas"],
            "grand terrace, ca": ["Inland Empire"],
            "grapevine, tx": ["Dallas"],
            "greeley, co": ["Denver"],
            "grimes, ia": ["Des Moines"],
            "grinnell, ia": ["Des Moines"],
            "guadalupe, az": ["Phoenix"],
            "gunter, tx": ["Dallas"],
            "guttenberg, nj": ["Newark"],
            "hacienda heights, ca": ["Inland Empire"],
            "hacienda hts, ca": ["Inland Empire"],
            "hackensack, nj": ["Newark"],
            "haddon heights, nj": ["Trenton"],
            "hainesport, nj": ["Trenton"],
            "haltom city, tx": ["Dallas"],
            "hamburg, nj": ["Newark"],
            "hamilton township, nj": ["Trenton"],
            "hammonton, nj": ["Trenton"],
            "hampton, nj": ["Newark"],
            "hanover, nj": ["Newark"],
            "harrisburg, pa": ["Trenton"],
            "harrison, nj": ["Newark"],
            "hasbrouck heights, nj": ["Newark"],
            "hastings, mn": ["Rochester"],
            "hatboro, pa": ["Trenton"],
            "hauppauge, ny": ["Newark"],
            "haverstraw, ny": ["Newark"],
            "hayward, ca": ["Bay Area"],
            "hemet, ca": ["Inland Empire"],
            "hempstead, ny": ["Newark"],
            "henderson, co": ["Denver"],
            "henderson, nv": ["Las Vegas"],
            "hesperia, ca": ["Inland Empire"],
            "hicksville, ny": ["Newark"],
            "highland, ca": ["Inland Empire"],
            "highland park, nj": ["Trenton", "Newark"],
            "highlands, tx": ["Houston"],
            "highlands ranch, co": ["Denver"],
            "hightstown, nj": ["Newark", "Trenton"],
            "hillsborough, nj": ["Newark"],
            "hillsborough township, nj": ["Trenton"],
            "hillside, nj": ["Newark"],
            "hoboken, nj": ["Newark"],
            "hockley, tx": ["Houston"],
            "holt, ca": ["Stockton"],
            "hopewell, nj": ["Trenton"],
            "houston, tx": ["Houston"],
            "huffman, tx": ["Houston"],
            "hughson, ca": ["Stockton"],
            "humble, tx": ["Houston"],
            "huntingdon valley, pa": ["Trenton"],
            "huntington beach, ca": ["Inland Empire"],
            "huntington station, ny": ["Newark"],
            "hutchins, tx": ["Dallas"],
            "idaho springs, co": ["Denver"],
            "indianola, ia": ["Des Moines"],
            "industry, ca": ["Inland Empire"],
            "inwood, ny": ["Newark"],
            "irvine, ca": ["Inland Empire"],
            "irving, tx": ["Dallas"],
            "irvington, nj": ["Newark"],
            "isleton, ca": ["Stockton"],
            "jamaica, ny": ["Newark"],
            "jefferson, nj": ["Newark"],
            "jenkintown, pa": ["Trenton"],
            "jericho, ny": ["Newark"],
            "jersey city, nj": ["Newark"],
            "jersey village, tx": ["Houston"],
            "johnston, ia": ["Des Moines"],
            "johnstown, co": ["Denver"],
            "joshua, tx": ["Dallas"],
            "jurupa valley, ca": ["Inland Empire"],
            "justin, tx": ["Dallas"],
            "kasson, mn": ["Rochester"],
            "katy, tx": ["Houston"],
            "kearny, nj": ["Newark"],
            "kellogg, ia": ["Des Moines"],
            "kellogg, mn": ["Rochester"],
            "kenilworth, nj": ["Newark"],
            "kennedale, tx": ["Dallas"],
            "kenvil, nj": ["Newark"],
            "keyport, nj": ["Trenton"],
            "king of prussia, pa": ["Trenton"],
            "kings park, ny": ["Newark"],
            "kiowa, co": ["Denver"],
            "knightsen, ca": ["Stockton"],
            "knoxville, ia": ["Des Moines"],
            "la habra, ca": ["Inland Empire"],
            "la marque, tx": ["Houston"],
            "la mirada, ca": ["Inland Empire"],
            "la porte, tx": ["Houston"],
            "la puente, ca": ["Inland Empire"],
            "lafayette, co": ["Denver"],
            "lafayette, nj": ["Newark"],
            "lafayette hill, pa": ["Trenton"],
            "laguna woods, ca": ["Inland Empire"],
            "lake city, mn": ["Rochester"],
            "lake dallas, tx": ["Dallas"],
            "lake elsinore, ca": ["Inland Empire"],
            "lake forest, ca": ["Inland Empire"],
            "lakewood, co": ["Denver"],
            "lakewood, nj": ["Newark"],
            "lambertville, nj": ["Trenton"],
            "lancaster, tx": ["Dallas"],
            "langhorne, pa": ["Trenton"],
            "lansdale, pa": ["Trenton"],
            "las vegas, nv": ["Las Vegas"],
            "lathrop, ca": ["Stockton"],
            "laveen village, az": ["Phoenix"],
            "lawnside, nj": ["Trenton"],
            "lawrence, ny": ["Newark"],
            "lawrence township, nj": ["Trenton"],
            "league city, tx": ["Houston"],
            "levittown, pa": ["Trenton"],
            "lewisville, tx": ["Dallas", "Houston"],
            "lime springs, ia": ["Rochester"],
            "lincoln, ca": ["Sacramento"],
            "linden, ca": ["Stockton"],
            "linden, nj": ["Newark"],
            "lindenwold, nj": ["Trenton"],
            "litchfield park, az": ["Phoenix"],
            "littlerock, ca": ["Inland Empire"],
            "littleton, co": ["Denver"],
            "livermore, ca": ["Stockton"],
            "lockeford, ca": ["Stockton"],
            "lodi, ca": ["Stockton"],
            "lodi, nj": ["Newark"],
            "logan township, nj": ["Trenton"],
            "loma linda, ca": ["Inland Empire"],
            "long beach, ca": ["Inland Empire"],
            "long island city, ny": ["Newark"],
            "longmont, co": ["Denver"],
            "los angeles, ca": ["Inland Empire"],
            "louisville, co": ["Denver"],
            "loveland, co": ["Denver"],
            "lucerne valley, ca": ["Inland Empire"],
            "lumberton township, nj": ["Trenton"],
            "lynbrook, ny": ["Newark"],
            "lyndhurst, nj": ["Newark"],
            "lynwood, ca": ["Inland Empire"],
            "macungie, pa": ["Trenton"],
            "madrid, ia": ["Des Moines"],
            "mahwah, nj": ["Newark", "Trenton"],
            "malvern, pa": ["Trenton"],
            "manalapan, nj": ["Newark"],
            "manhasset, ny": ["Newark"],
            "mansfield, nj": ["Trenton"],
            "manteca, ca": ["Stockton"],
            "mantorville, mn": ["Rochester"],
            "mantua township, nj": ["Trenton"],
            "manvel, tx": ["Houston"],
            "manville, nj": ["Newark", "Trenton"],
            "maple shade, nj": ["Trenton"],
            "maplewood, nj": ["Newark"],
            "march air reserve base, ca": ["Inland Empire"],
            "maricopa, az": ["Phoenix"],
            "marlboro township, nj": ["Newark"],
            "marshalltown, ia": ["Des Moines"],
            "maspeth, ny": ["Newark"],
            "maywood, nj": ["Newark"],
            "mcclellan park, ca": ["Sacramento"],
            "mckinney, tx": ["Dallas"],
            "mead valley, ca": ["Inland Empire"],
            "medford, mn": ["Rochester"],
            "melville, ny": ["Newark"],
            "menifee, ca": ["Inland Empire"],
            "merchantville, nj": ["Trenton"],
            "mesa, az": ["Phoenix"],
            "mesa, az, us": ["Phoenix"],
            "mesquite, tx": ["Dallas"],
            "metuchen, nj": ["Newark"],
            "mickleton, nj": ["Trenton"],
            "middle village, ny": ["Newark"],
            "middlesex, nj": ["Newark"],
            "middletown, nj": ["Newark"],
            "midlothian, tx": ["Dallas"],
            "millwood, ny": ["Newark"],
            "mineola, ny": ["Newark"],
            "minnesota city, mn": ["Rochester"],
            "mission viejo, ca": ["Inland Empire"],
            "missouri city, tx": ["Houston"],
            "mitchellville, ia": ["Des Moines"],
            "modesto, ca": ["Stockton"],
            "monmouth junction, nj": ["Newark"],
            "monroe, ny": ["Newark"],
            "monroe township, nj": ["Trenton"],
            "monroeville, nj": ["Trenton"],
            "mont belvieu, tx": ["Houston"],
            "montclair, nj": ["Newark"],
            "monterey park, ca": ["Inland Empire"],
            "montville, nj": ["Newark"],
            "monument, co": ["Denver"],
            "moraga, ca": ["Bay Area"],
            "moreno valley, ca": ["Inland Empire"],
            "morganville, nj": ["Newark"],
            "morris plains, nj": ["Newark"],
            "morristown, nj": ["Newark"],
            "morrisville, pa": ["Trenton"],
            "mount holly, nj": ["Trenton"],
            "mount kisco, ny": ["Newark"],
            "mount vernon, ny": ["Newark"],
            "mountain house, ca": ["Stockton"],
            "mountain view, ca": ["Bay Area"],
            "mountainside, nj": ["Newark"],
            "mt ephraim, nj": ["Trenton"],
            "mt holly, nj": ["Trenton"],
            "mt laurel township, nj": ["Trenton"],
            "mt vernon, ny": ["Newark"],
            "mt. laurel township, nj": ["Trenton"],
            "mullica hill, nj": ["Trenton"],
            "murrieta, ca": ["Inland Empire"],
            "n las vegas, nv": ["Las Vegas"],
            "nanuet, ny": ["Trenton"],
            "napa, ca": ["Bay Area", "Sacramento"],
            "nassau county, ny": ["Newark"],
            "nazareth, pa": ["Trenton"],
            "nederland, co": ["Denver"],
            "nevada, ia": ["Des Moines"],
            "new brunswick, nj": ["Newark", "Trenton"],
            "new canaan, ct": ["Trenton"],
            "new caney, tx": ["Houston"],
            "new city, ny": ["Newark"],
            "new hampton, ny": ["Newark"],
            "new hope, pa": ["Newark", "Trenton"],
            "new hyde park, ny": ["Newark"],
            "new jerusalem, ca": ["Stockton"],
            "new providence, nj": ["Newark"],
            "new river, az": ["Phoenix"],
            "new rochelle, ny": ["Trenton"],
            "new york, ny": ["Newark"],
            "new york city, ny": ["Newark"],
            "newark, ca": ["Bay Area"],
            "newark, nj": ["Newark"],
            "newark liberty international airport, nj": ["Newark"],
            "newfoundland, nj": ["Newark"],
            "newman, ca": ["Stockton"],
            "newport beach, ca": ["Inland Empire"],
            "newton, ia": ["Des Moines"],
            "norco, ca": ["Inland Empire"],
            "norristown, pa": ["Trenton"],
            "north arlington, nj": ["Newark"],
            "north bergen, nj": ["Newark"],
            "north brunswick, nj": ["Newark"],
            "north brunswick township, nj": ["Newark"],
            "north highlands, ca": ["Sacramento", "Stockton"],
            "north las vegas, nv": ["Las Vegas"],
            "north palm springs, ca": ["Inland Empire"],
            "north richland hills, tx": ["Dallas"],
            "northfield, mn": ["Rochester"],
            "northport, ny": ["Newark"],
            "norwalk, ca": ["Inland Empire"],
            "norwalk, ct": ["Newark"],
            "norwalk, ia": ["Des Moines"],
            "novato, ca": ["Bay Area"],
            "nyack, ny": ["Newark"],
            "oakdale, ca": ["Stockton"],
            "oakland, ca": ["Bay Area"],
            "oaklyn, nj": ["Trenton"],
            "oceanside, ny": ["Newark"],
            "old bridge, nj": ["Trenton", "Newark"],
            "old rvr-wnfre, tx": ["Houston"],
            "ontario, ca": ["Inland Empire"],
            "oradell, nj": ["Newark"],
            "orange, ca": ["Inland Empire"],
            "orangeburg, ny": ["Newark"],
            "orangevale, ca": ["Stockton", "Sacramento"],
            "oro grande, ca": ["Inland Empire"],
            "osceola, ia": ["Des Moines"],
            "ottsville, pa": ["Trenton"],
            "owatonna, mn": ["Rochester"],
            "palm springs, ca": ["Inland Empire"],
            "palmyra, nj": ["Trenton"],
            "palo alto, ca": ["Bay Area"],
            "panora, ia": ["Des Moines"],
            "paoli, pa": ["Trenton"],
            "paradise, nv": ["Las Vegas"],
            "paradise valley, az": ["Phoenix"],
            "paramount, ca": ["Inland Empire"],
            "paramus, nj": ["Newark"],
            "parker, co": ["Denver"],
            "parsippany-troy hills, nj": ["Newark"],
            "pasadena, ca": ["Inland Empire"],
            "pasadena, tx": ["Houston"],
            "passaic, nj": ["Newark"],
            "paterson, nj": ["Newark"],
            "patterson, ca": ["Stockton"],
            "peapack, nj": ["Newark"],
            "pearland, tx": ["Houston"],
            "peekskill, ny": ["Trenton"],
            "pelham manor, ny": ["Newark"],
            "pella, ia": ["Des Moines"],
            "pemberton township, nj": ["Trenton"],
            "penndel, pa": ["Trenton"],
            "pennsauken, nj": ["Trenton"],
            "peoria, az": ["Phoenix"],
            "perkiomenville, pa": ["Trenton"],
            "perris, ca": ["Inland Empire"],
            "perry, ia": ["Des Moines"],
            "perth amboy, nj": ["Newark", "Trenton"],
            "phelan, ca": ["Inland Empire"],
            "philadelphia, pa": ["Trenton"],
            "phillips ranch, ca": ["Inland Empire"],
            "phillipsburg, nj": ["Trenton"],
            "phoenix, az": ["Phoenix"],
            "phoenix, az, us": ["Phoenix"],
            "phoenixville, pa": ["Trenton"],
            "pilot hill, ca": ["Sacramento"],
            "pine island, mn": ["Rochester"],
            "pinole, ca": ["Bay Area"],
            "piscataway, nj": ["Newark"],
            "pittsburg, ca": ["Stockton", "Bay Area", "Sacramento"],
            "placerville, ca": ["Sacramento"],
            "plainfield, nj": ["Newark"],
            "plainview, ny": ["Newark"],
            "plano, tx": ["Dallas"],
            "platteville, co": ["Denver"],
            "pleasant grove, ca": ["Sacramento"],
            "pleasant hill, ia": ["Des Moines"],
            "pleasanton, ca": ["Bay Area"],
            "plymouth meeting, pa": ["Trenton"],
            "pomona, ca": ["Inland Empire"],
            "port chester, ny": ["Newark"],
            "port reading, nj": ["Newark"],
            "port washington, ny": ["Newark"],
            "porter, tx": ["Houston"],
            "portola valley, ca": ["Bay Area"],
            "pottstown, pa": ["Trenton"],
            "prairie city, ia": ["Des Moines"],
            "prescott valley, az": ["Phoenix"],
            "princeton, nj": ["Trenton", "Newark"],
            "princeton junction, nj": ["Trenton"],
            "prosper, tx": ["Dallas"],
            "putnam valley, ny": ["Newark"],
            "quakertown, pa": ["Trenton"],
            "queen creek, az": ["Phoenix"],
            "queens, ny": ["Newark"],
            "racine, mn": ["Rochester"],
            "rahway, nj": ["Newark"],
            "rancho cordova, ca": ["Stockton", "Sacramento"],
            "rancho cucamonga, ca": ["Inland Empire"],
            "raritan, nj": ["Newark"],
            "red bank, nj": ["Trenton"],
            "red wing, mn": ["Rochester"],
            "redlands, ca": ["Inland Empire"],
            "redwood city, ca": ["Bay Area"],
            "rhome, tx": ["Dallas"],
            "rialto, ca": ["Inland Empire"],
            "richardson, tx": ["Dallas"],
            "richmond, ca": ["Bay Area"],
            "richmond, tx": ["Houston"],
            "ridgefield park, nj": ["Newark"],
            "ridgewood, ny": ["Newark"],
            "rio oso, ca": ["Sacramento"],
            "ripon, ca": ["Stockton"],
            "riverbank, ca": ["Stockton"],
            "riverdale, nj": ["Newark"],
            "riverside, ca": ["Inland Empire"],
            "riverside, nj": ["Trenton"],
            "riverton, nj": ["Trenton"],
            "rochester, mn": ["Rochester"],
            "rockaway, nj": ["Newark"],
            "rocklin, ca": ["Sacramento"],
            "rockwall, tx": ["Dallas"],
            "rohnert park, ca": ["Bay Area"],
            "roseland, nj": ["Newark"],
            "roselle, nj": ["Newark"],
            "roselle park, nj": ["Newark"],
            "rosemead, ca": ["Inland Empire"],
            "rosenberg, tx": ["Houston"],
            "roseville, ca": ["Sacramento", "Stockton"],
            "rosharon, tx": ["Houston"],
            "rowlett, tx": ["Dallas"],
            "royse city, tx": ["Dallas"],
            "rushford, mn": ["Rochester"],
            "sacramento, ca": ["Stockton", "Sacramento"],
            "salida, ca": ["Stockton"],
            "san anselmo, ca": ["Bay Area"],
            "san bernardino, ca": ["Inland Empire"],
            "san bruno, ca": ["Bay Area"],
            "san carlos, ca": ["Bay Area"],
            "san clemente, ca": ["Inland Empire"],
            "san francisco, ca": ["Bay Area"],
            "san francisco bay area, ca": ["Bay Area"],
            "san jacinto, ca": ["Inland Empire"],
            "san jose, ca": ["Bay Area"],
            "san juan capistrano, ca": ["Inland Empire"],
            "san leandro, ca": ["Bay Area"],
            "san leon, tx": ["Houston"],
            "san mateo, ca": ["Bay Area"],
            "san rafael, ca": ["Bay Area"],
            "san tan valley, az": ["Phoenix"],
            "santa ana, ca": ["Inland Empire"],
            "santa fe, tx": ["Houston"],
            "santa fe springs, ca": ["Inland Empire"],
            "santa rosa, ca": ["Bay Area"],
            "sayreville, nj": ["Trenton"],
            "scottsdale, az": ["Phoenix"],
            "seabrook, tx": ["Houston"],
            "secaucus, nj": ["Newark"],
            "sharon hill, pa": ["Trenton"],
            "shenandoah, tx": ["Houston"],
            "shingle springs, ca": ["Sacramento"],
            "signal hill, ca": ["Inland Empire"],
            "skillman, nj": ["Trenton"],
            "sloan, nv": ["Las Vegas"],
            "somerset, nj": ["Newark"],
            "somerville, nj": ["Trenton", "Newark"],
            "souderton, pa": ["Trenton"],
            "south houston, tx": ["Houston"],
            "south plainfield, nj": ["Newark"],
            "south river, nj": ["Trenton"],
            "south salem, ny": ["Newark", "Trenton"],
            "south san francisco, ca": ["Bay Area"],
            "southampton, pa": ["Trenton"],
            "southampton township, nj": ["Trenton"],
            "southlake, tx": ["Dallas"],
            "sparta, nj": ["Newark"],
            "spring, tx": ["Houston"],
            "spring city, pa": ["Trenton"],
            "spring valley, mn": ["Rochester"],
            "spring valley, nv": ["Las Vegas"],
            "spring valley, ny": ["Trenton", "Newark"],
            "springfield, nj": ["Newark"],
            "st charles, mn": ["Rochester"],
            "stafford, tx": ["Houston"],
            "stamford, ct": ["Newark", "Trenton"],
            "stanford, ca": ["Bay Area"],
            "stanhope, nj": ["Newark"],
            "stanton, ca": ["Inland Empire"],
            "staten island, ny": ["Newark"],
            "stewartville, mn": ["Rochester"],
            "stockton, ca": ["Stockton", "Sacramento", "Bay Area"],
            "stroudsburg, pa": ["Trenton"],
            "suffern, ny": ["Trenton"],
            "sugar land, tx": ["Houston"],
            "suisun city, ca": ["Bay Area", "Sacramento"],
            "summit, nj": ["Newark"],
            "sun city, az": ["Phoenix"],
            "sun city west, az": ["Phoenix"],
            "sunnyvale, ca": ["Bay Area"],
            "sunnyvale, tx": ["Dallas"],
            "sunrise manor, nv": ["Las Vegas"],
            "surprise, az": ["Phoenix"],
            "swedesboro, nj": ["Trenton"],
            "syosset, ny": ["Trenton"],
            "teaneck, nj": ["Newark"],
            "temecula, ca": ["Inland Empire"],
            "tempe, az": ["Phoenix"],
            "tempe, az, us": ["Phoenix"],
            "teterboro, nj": ["Newark"],
            "texas city, tx": ["Houston"],
            "the colony, tx": ["Dallas"],
            "the woodlands, tx": ["Houston"],
            "thornton, co": ["Denver"],
            "tolleson, az": ["Phoenix"],
            "tomball, tx": ["Houston"],
            "toms river, nj": ["Trenton"],
            "township of brick, nj": ["Newark"],
            "township of deptford, nj": ["Trenton"],
            "township of howell, nj": ["Newark"],
            "township of jackson, nj": ["Newark"],
            "township of monroe, nj": ["Newark"],
            "tracy, ca": ["Stockton", "Bay Area"],
            "trenton, nj": ["Newark", "Trenton"],
            "trevose, pa": ["Trenton"],
            "turlock, ca": ["Stockton"],
            "twin oaks, pa": ["Trenton"],
            "union, nj": ["Newark"],
            "union city, ca": ["Bay Area"],
            "union city, nj": ["Newark"],
            "upland, ca": ["Inland Empire"],
            "urbandale, ia": ["Des Moines"],
            "vacaville, ca": ["Bay Area", "Sacramento"],
            "vale, ca": ["Stockton"],
            "valhalla, ny": ["Newark"],
            "valley cottage, ny": ["Newark"],
            "van meter, ia": ["Des Moines"],
            "vernon, ca": ["Inland Empire"],
            "victorville, ca": ["Inland Empire"],
            "vineland, nj": ["Trenton"],
            "voorhees township, nj": ["Trenton"],
            "wabasha, mn": ["Rochester"],
            "waddell, az": ["Phoenix"],
            "waldwick, nj": ["Newark"],
            "waller, tx": ["Houston"],
            "walnut creek, ca": ["Bay Area"],
            "walnut grove, ca": ["Bay Area"],
            "warren, nj": ["Newark"],
            "warrington, pa": ["Trenton"],
            "washington, nj": ["Newark"],
            "watauga, tx": ["Dallas"],
            "watchung, nj": ["Newark"],
            "waukee, ia": ["Des Moines"],
            "waxahachie, tx": ["Dallas"],
            "wayne, nj": ["Newark"],
            "weatherford, tx": ["Dallas"],
            "west babylon, ny": ["Newark"],
            "west berlin, nj": ["Trenton"],
            "west caldwell, nj": ["Newark"],
            "west chester, pa": ["Trenton"],
            "west columbia, tx": ["Houston"],
            "west concord, mn": ["Rochester"],
            "west covina, ca": ["Inland Empire"],
            "west deptford, nj": ["Trenton"],
            "west des moines, ia": ["Des Moines"],
            "west haverstraw, ny": ["Newark"],
            "west milford, nj": ["Newark"],
            "west new york, nj": ["Newark"],
            "west orange, nj": ["Newark"],
            "west sacramento, ca": ["Sacramento", "Stockton"],
            "west university place, tx": ["Houston"],
            "westampton, nj": ["Trenton"],
            "westampton township, nj": ["Trenton"],
            "westley, ca": ["Stockton"],
            "westminster, co": ["Denver"],
            "westwood, nj": ["Newark"],
            "white plains, ny": ["Newark"],
            "whitehouse station, nj": ["Newark"],
            "whitney, nv": ["Las Vegas"],
            "wildomar, ca": ["Inland Empire"],
            "williamstown, nj": ["Trenton"],
            "willingboro, nj": ["Trenton"],
            "wilmer, tx": ["Dallas"],
            "winchester, nv": ["Las Vegas"],
            "windsor, nj": ["Newark"],
            "windsor heights, ia": ["Des Moines"],
            "winona, mn": ["Rochester"],
            "winterset, ia": ["Des Moines"],
            "wood-ridge, nj": ["Newark"],
            "woodbridge, nj": ["Newark"],
            "woodbridge township, nj": ["Newark", "Trenton"],
            "woodbury, nj": ["Trenton"],
            "woodbury, ny": ["Trenton"],
            "woodland, ca": ["Sacramento"],
            "woodside, ny": ["Newark"],
            "woolwich township, nj": ["Trenton"],
            "wrightstown, nj": ["Trenton"],
            "wyckoff, nj": ["Newark"],
            "wylie, tx": ["Dallas"],
            "yardley, pa": ["Trenton"],
            "yonkers, ny": ["Newark"],
            "yorktown, ny": ["Newark"],
            "yuba city, ca": ["Sacramento"],
            "zumbrota, mn": ["Rochester"],
        
            "adelanto, ca": ['Inland Empire'],
            "afton, ia": ['Des Moines'],
            "alameda, ca": ['Bay Area'],
            "albany, ca": ['Bay Area'],
            "albert lea, mn": ['Rochester'],
            "alburtis, pa": ['Trenton'],
            "aliso viejo, ca": ['Inland Empire'],
            "allamuchy, nj": ['Newark'],
            "altadena, ca": ['Inland Empire'],
            "altura, mn": ['Rochester'],
            "alvarado, tx": ['Dallas'],
            "ambler, pa": ['Trenton'],
            "american canyon, ca": ['Bay Area'],
            "andyville, mn": ['Rochester'],
            "anna, tx": ['Dallas'],
            "antelope, ca": ['Sacramento'],
            "anthem, az": ['Phoenix'],
            "apache jct, az": ['Phoenix'],
            "apple valley, ca": ['Inland Empire'],
            "apple valley, mn": ['Rochester'],
            "applegate, ca": ['Sacramento'],
            "ardmore, pa": ['Trenton'],
            "ashland, ca": ['Sacramento'],
            "aspen park, co": ['Denver'],
            "aston, pa": ['Trenton'],
            "astoria, ny": ['Newark'],
            "atascocita, tx": ['Houston'],
            "atherton, ca": ['Bay Area'],
            "august, ca": ['Sacramento'],
            "azle, tx": ['Dallas'],
            "bailey, co": ['Denver'],
            "baldwin park, ca": ['Inland Empire'],
            "bapchule, az": ['Phoenix'],
            "basking ridge, nj": ['Newark'],
            "bath, pa": ['Trenton'],
            "baxter, ia": ['Des Moines'],
            "bay point, ca": ['Sacramento'],
            "bayou vista, tx": ['Houston'],
            "beale afb, ca": ['Sacramento'],
            "bedford, tx": ['Dallas'],
            "bedford-stuyvesant, ny": ['Newark'],
            "bedminster, pa": ['Trenton'],
            "bellechester, mn": ['Rochester'],
            "benbrook, tx": ['Dallas'],
            "bennett, co": ['Denver'],
            "bergen point, nj": ['Newark'],
            "berthoud, co": ['Denver'],
            "berwick, ia": ['Des Moines'],
            "berwyn, pa": ['Trenton'],
            "bethel island, ca": ['Sacramento'],
            "big bear lake, ca": ['Inland Empire'],
            "big bear, ca": ['Inland Empire'],
            "birds landing, ca": ['Sacramento'],
            "black hawk, co": ['Denver'],
            "blooming prairie, mn": ['Rochester'],
            "bobville, tx": ['Houston'],
            "boling, tx": ['Houston'],
            "bonney, tx": ['Houston'],
            "bow mar, co": ['Denver'],
            "breinigsville, pa": ['Trenton'],
            "brookhaven, pa": ['Trenton'],
            "brookside village, tx": ['Houston'],
            "broomall, pa": ['Trenton'],
            "brownsdale, mn": ['Rochester'],
            "bryn athyn, pa": ['Trenton'],
            "bryn mawr, pa": ['Trenton'],
            "burleson, tx": ['Dallas'],
            "burnsville, mn": ['Rochester'],
            "byers, co": ['Denver'],
            "cameron park, ca": ['Bay Area'],
            "canton, mn": ['Rochester'],
            "carefree, az": ['Phoenix'],
            "carmichael, ca": ['Sacramento'],
            "casey, ia": ['Des Moines'],
            "castle pines, co": ['Denver'],
            "cedar knolls, nj": ['Newark'],
            "cedarhurst, ny": ['Newark'],
            "celina, tx": ['Dallas'],
            "chatham, nj": ['Newark'],
            "cherry hills village, co": ['Denver'],
            "cherry valley, ca": ['Inland Empire'],
            "chester springs, pa": ['Trenton'],
            "chester, nj": ['Newark'],
            "cinco ranch, tx": ['Houston'],
            "city industry, ca": ['Inland Empire'],
            "claremont, ca": ['Inland Empire'],
            "clarks grove, mn": ['Rochester'],
            "clarksburg, ca": ['Sacramento'],
            "clarksburg, nj": ['Newark'],
            "clayton, ca": ['Bay Area'],
            "cleburne, tx": ['Dallas'],
            "clinton, nj": ['Newark'],
            "cloverleaf, tx": ['Houston'],
            "clute, tx": ['Houston'],
            "cockrell hill, tx": ['Dallas'],
            "colfax, ia": ['Des Moines'],
            "college point, ny": ['Newark'],
            "collegeville, pa": ['Trenton'],
            "collingdale, pa": ['Trenton'],
            "colo, ia": ['Des Moines'],
            "columbine, co": ['Denver'],
            "coolidge, az": ['Phoenix'],
            "coopersburg, pa": ['Trenton'],
            "corinth, tx": ['Dallas'],
            "corral city, tx": ['Dallas'],
            "corte madera, ca": ['Bay Area'],
            "cotati, ca": ['Bay Area'],
            "cottage grove, mn": ['Rochester'],
            "courtland, ca": ['Sacramento'],
            "covina, ca": ['Inland Empire'],
            "crag, az": ['Phoenix'],
            "cranbury, nj": ['Newark'],
            "cressey, ca": ['Inland Empire'],
            "crosby, tx": ['Houston'],
            "crowley, tx": ['Dallas'],
            "crows landing, ca": ['Inland Empire'],
            "cupertino, ca": ['Inland Empire'],
            "cypress, ca": ['Inland Empire'],
            "dacono, co": ['Denver'],
            "dallas county, tx": ['Dallas'],
            "dana point, ca": ['Inland Empire'],
            "danville, ca": ['Bay Area'],
            "deer park, ny": ['Newark'],
            "denair, ca": ['Inland Empire'],
            "dennison, mn": ['Rochester'],
            "denville, nj": ['Newark'],
            "desert hot springs, ca": ['Inland Empire'],
            "devore heights, ca": ['Inland Empire'],
            "dexter, mn": ['Rochester'],
            "diablo, ca": ['Bay Area'],
            "diamond bar, ca": ['Inland Empire'],
            "dixon, ca": ['Bay Area'],
            "dover, mn": ['Rochester'],
            "drexel hill, pa": ['Trenton'],
            "duarte, ca": ['Inland Empire'],
            "dublin, ca": ['Bay Area'],
            "dundas, mn": ['Rochester'],
            "dunnigan, ca": ['Sacramento'],
            "dupont, co": ['Denver'],
            "dyersdale, tx": ['Houston'],
            "east lansdowne, pa": ['Trenton'],
            "east newark, nj": ['Newark'],
            "east norriton, pa": ['Trenton'],
            "east palo alto, ca": ['Bay Area'],
            "east rutherford, nj": ['Newark'],
            "east texas, pa": ['Trenton'],
            "el cerrito, ca": ['Bay Area'],
            "el sobrante, ca": ['Bay Area'],
            "elkhart, ia": ['Des Moines'],
            "elko new market, mn": ['Rochester'],
            "elkton, mn": ['Rochester'],
            "ellendale, mn": ['Rochester'],
            "ellsworth, wi": ['Rochester'],
            "elmira, ca": ['Sacramento'],
            "erie, co": ['Denver'],
            "etter, mn": ['Rochester'],
            "evans, co": ['Denver'],
            "evergreen, co": ['Denver'],
            "fair oaks, ca": ['Sacramento'],
            "fairfax, ca": ['Bay Area'],
            "fanwood, nj": ['Newark'],
            "farmers branch, tx": ['Dallas'],
            "farmingdale, nj": ['Newark'],
            "fate, tx": ['Dallas'],
            "feasterville, pa": ['Trenton'],
            "flanders, nj": ['Newark'],
            "florence, az": ['Phoenix'],
            "florin, ca": ['Sacramento'],
            "forked river, nj": ['Newark'],
            "foster city, ca": ['Bay Area'],
            "fountain hill, pa": ['Trenton'],
            "fountain hills, az": ['Phoenix'],
            "fountain, mn": ['Rochester'],
            "foxfield, co": ['Denver'],
            "freemansburg, pa": ['Trenton'],
            "fresno, tx": ['Houston'],
            "frontenac, mn": ['Rochester'],
            "fullerton, pa": ['Trenton'],
            "furlong, pa": ['Trenton'],
            "galesburg, ia": ['Des Moines'],
            "genesee, co": ['Denver'],
            "geneva, mn": ['Rochester'],
            "gila bend, az": ['Phoenix'],
            "glen ellen, ca": ['Bay Area'],
            "glen mills, pa": ['Trenton'],
            "glen riddle, pa": ['Trenton'],
            "glendale, co": ['Denver'],
            "glendale, ny": ['Newark'],
            "glendon, pa": ['Trenton'],
            "glendora, ca": ['Inland Empire'],
            "gleneagle, co": ['Denver'],
            "glenn heights, tx": ['Dallas'],
            "gloucester city, nj": ['Newark'],
            "gold river, ca": ['Sacramento'],
            "goodhue, mn": ['Rochester'],
            "grandview, tx": ['Dallas'],
            "granger, ia": ['Des Moines'],
            "grass valley, ca": ['Sacramento'],
            "green mountain, co": ['Denver'],
            "greenville, tx": ['Dallas'],
            "greenwood village, co": ['Denver'],
            "guthrie center, ia": ['Des Moines'],
            "half moon bay, ca": ['Bay Area'],
            "hampton, mn": ['Rochester'],
            "hardin, tx": ['Houston'],
            "harleysville, pa": ['Trenton'],
            "harmony, mn": ['Rochester'],
            "haslet, tx": ['Dallas'],
            "hatfield, pa": ['Trenton'],
            "haverford, pa": ['Trenton'],
            "havertown, pa": ['Trenton'],
            "hayfield, mn": ['Rochester'],
            "hayward, mn": ['Rochester'],
            "helendale, ca": ['Inland Empire'],
            "hellertown, pa": ['Trenton'],
            "hempstead, tx": ['Houston'],
            "hillsborough, ca": ['Bay Area'],
            "hilmar, ca": ['Inland Empire'],
            "hokendauqua, pa": ['Trenton'],
            "holland, pa": ['Trenton'],
            "hollandale, mn": ['Rochester'],
            "holly hill, pa": ['Trenton'],
            "hood, ca": ['Sacramento'],
            "hope, mn": ['Rochester'],
            "horsham, pa": ['Trenton'],
            "houston, mn": ['Rochester'],
            "hudson, co": ['Denver'],
            "hudson, wi": ['Rochester'],
            "hunters creek village, tx": ['Houston'],
            "huntington, ny": ['Newark'],
            "hygiene, co": ['Denver'],
            "indian hills, co": ['Denver'],
            "indian springs, nv": ['Las Vegas'],
            "inver grove heights, mn": ['Rochester'],
            "irwindale, ca": ['Inland Empire'],
            "island park, ny": ['Newark'],
            "italy, tx": ['Dallas'],
            "ivyland, pa": ['Trenton'],
            "jacinto city, tx": ['Houston'],
            "jackson, ca": ['Sacramento'],
            "jamestown, co": ['Denver'],
            "jean, nv": ['Las Vegas'],
            "jefferson, co": ['Denver'],
            "jefferson, ia": ['Des Moines'],
            "johnsburg, mn": ['Rochester'],
            "kaufman, tx": ['Dallas'],
            "keasbey, nj": ['Newark'],
            "keene, tx": ['Dallas'],
            "keenesburg, co": ['Denver'],
            "keller, tx": ['Dallas'],
            "kenyon, mn": ['Rochester'],
            "kew gardens hills, ny": ['Newark'],
            "keyes, ca": ['Inland Empire'],
            "kimberton, pa": ['Trenton'],
            "kingwood, tx": ['Houston'],
            "kintnersville, pa": ['Trenton'],
            "klein, tx": ['Houston'],
            "krugerville, tx": ['Dallas'],
            "la riviera, ca": ['Sacramento'],
            "la verne, ca": ['Inland Empire'],
            "lafayette, ca": ['Bay Area'],
            "laguna beach, ca": ['Inland Empire'],
            "laguna hills, ca": ['Inland Empire'],
            "laguna niguel, ca": ['Inland Empire'],
            "lake elmo, mn": ['Rochester'],
            "lakeside, co": ['Denver'],
            "lakeville, mn": ['Rochester'],
            "lakewood, ca": ['Inland Empire'],
            "lanesboro, mn": ['Rochester'],
            "lansdowne, pa": ['Trenton'],
            "lansing, mn": ['Rochester'],
            "las flores, ca": ['Inland Empire'],
            "laurel hollow, ny": ['Newark'],
            "laveen, az": ['Phoenix'],
            "le roy, mn": ['Rochester'],
            "lehman, pa": ['Trenton'],
            "lewiston, mn": ['Rochester'],
            "liberty, tx": ['Houston'],
            "limerick, pa": ['Trenton'],
            "lindenhurst, ny": ['Newark'],
            "little elm, tx": ['Dallas'],
            "live oak, ca": ['Sacramento'],
            "livingston, nj": ['Newark'],
            "lone tree, co": ['Denver'],
            "long beach, ny": ['Newark'],
            "long hill, nj": ['Newark'],
            "long island, ny": ['Newark'],
            "loomis, ca": ['Sacramento'],
            "los alamitos, ca": ['Inland Empire'],
            "los altos, ca": ['Inland Empire'],
            "los gatos, ca": ['Inland Empire'],
            "lotus, ca": ['Sacramento'],
            "louviers, co": ['Denver'],
            "lucas, ia": ['Des Moines'],
            "luther, ia": ['Des Moines'],
            "lyle, mn": ['Rochester'],
            "lyons, co": ['Denver'],
            "lytle creek, ca": ['Inland Empire'],
            "mabel, mn": ['Rochester'],
            "madison, nj": ['Newark'],
            "magnolia, tx": ['Houston'],
            "manhattan, ny": ['Newark'],
            "mansfield, tx": ['Dallas'],
            "martinez, ca": ['Bay Area'],
            "marysville, ca": ['Sacramento'],
            "maypearl, tx": ['Dallas'],
            "mazeppa, mn": ['Rochester'],
            "mc intire, ia": ['Des Moines'],
            "mead, co": ['Denver'],
            "media, pa": ['Trenton'],
            "melcher-dallas, ia": ['Des Moines'],
            "melissa, tx": ['Dallas'],
            "menlo park, ca": ['Bay Area'],
            "meridian, co": ['Denver'],
            "merion view, pa": ['Trenton'],
            "merrick, ny": ['Newark'],
            "miesville, mn": ['Rochester'],
            "mill valley, ca": ['Bay Area'],
            "millburn, nj": ['Newark'],
            "milliken, co": ['Denver'],
            "millville, mn": ['Rochester'],
            "milpitas, ca": ['Bay Area'],
            "minn city, mn": ['Rochester'],
            "minneapolis, mn": ['Rochester'],
            "mira loma, ca": ['Inland Empire'],
            "mission bend, tx": ['Houston'],
            "moapa valley, nv": ['Las Vegas'],
            "moapa, nv": ['Las Vegas'],
            "mobile, az": ['Phoenix'],
            "moland, mn": ['Rochester'],
            "monroe, ia": ['Des Moines'],
            "monrovia, ca": ['Inland Empire'],
            "montclair, ca": ['Inland Empire'],
            "montebello, ca": ['Inland Empire'],
            "montgomery, tx": ['Houston'],
            "moonachie, nj": ['Newark'],
            "morrison, co": ['Denver'],
            "morristown, mn": ['Rochester'],
            "mountain lakes, nj": ['Newark'],
            "mountain springs, nv": ['Las Vegas'],
            "murray, ia": ['Des Moines'],
            "muscoy, ca": ['Inland Empire'],
            "narberth, pa": ['Trenton'],
            "needville, tx": ['Houston'],
            "neffs, pa": ['Trenton'],
            "nellis afb, nv": ['Las Vegas'],
            "nerstrand, mn": ['Rochester'],
            "netcong, nj": ['Newark'],
            "new britain, pa": ['Trenton'],
            "new virginia, ia": ['Des Moines'],
            "new waverly, tx": ['Houston'],
            "newcastle, ca": ['Bay Area'],
            "newtown, pa": ['Trenton'],
            "nicolaus, ca": ['Sacramento'],
            "north plainfield, nj": ['Newark'],
            "north wales, pa": ['Trenton'],
            "northampton, pa": ['Trenton'],
            "northglenn, co": ['Denver'],
            "northlake, tx": ['Dallas'],
            "oakley, ca": ['Sacramento'],
            "olivehurst, ca": ['Sacramento'],
            "oreland, pa": ['Trenton'],
            "oronoco, mn": ['Rochester'],
            "ossining, ny": ['Newark'],
            "ostrander, mn": ['Rochester'],
            "otranto, ia": ['Des Moines'],
            "oxford, ca": ['Inland Empire'],
            "ozone park, ny": ['Newark'],
            "pacifica, ca": ['Bay Area'],
            "pahrump, nv": ['Las Vegas'],
            "palo verde, az": ['Phoenix'],
            "parker, tx": ['Dallas'],
            "parkway, ca": ['Sacramento'],
            "patrick, tx": ['Dallas'],
            "pecan grove, tx": ['Houston'],
            "pecan hill, tx": ['Dallas'],
            "penn valley, pa": ['Trenton'],
            "perkasie, pa": ['Trenton'],
            "petaluma, ca": ['Bay Area'],
            "peterson, mn": ['Rochester'],
            "pickwick, mn": ['Rochester'],
            "pico rivera, ca": ['Inland Empire'],
            "pine, co": ['Denver'],
            "pinehurst, tx": ['Dallas'],
            "piney point village, tx": ['Houston'],
            "pipersville, pa": ['Trenton'],
            "placentia, ca": ['Inland Empire'],
            "plainview, co": ['Denver'],
            "plainview, mn": ['Rochester'],
            "plantersville, tx": ['Houston'],
            "pleasant hill, ca": ['Bay Area'],
            "plumas lake, ca": ['Sacramento'],
            "point reyes station, ca": ['Bay Area'],
            "potsdam, mn": ['Rochester'],
            "preston, mn": ['Rochester'],
            "prole, ia": ['Des Moines'],
            "prospect park, pa": ['Trenton'],
            "protivin, ia": ['Des Moines'],
            "rancho santa margarita, ca": ['Inland Empire'],
            "randolph, mn": ['Rochester'],
            "reads landing, mn": ['Rochester'],
            "red oak, tx": ['Dallas'],
            "rego park, ny": ['Newark'],
            "riceville, ia": ['Des Moines'],
            "richboro, pa": ['Trenton'],
            "richwood, tx": ['Houston'],
            "ridley park, pa": ['Trenton'],
            "rio linda, ca": ['Sacramento'],
            "rio verde, az": ['Phoenix'],
            "rio vista, ca": ['Sacramento'],
            "river falls, wi": ['Rochester'],
            "roanoke, tx": ['Dallas'],
            "robbiinsville, nj": ['Newark'],
            "rockville centre, ny": ['Newark'],
            "rollingstone, mn": ['Rochester'],
            "roman forest, tx": ['Houston'],
            "rose creek, mn": ['Rochester'],
            "rose valley, pa": ['Trenton'],
            "rosedale, ny": ['Newark'],
            "rosemont, ca": ['Inland Empire'],
            "rosemount, mn": ['Rochester'],
            "roslyn, pa": ['Trenton'],
            "ross, ca": ['Bay Area'],
            "rowland heights, ca": ['Inland Empire'],
            "sacate, az": ['Phoenix'],
            "sacaton, az": ['Phoenix'],
            "saginaw, tx": ['Dallas'],
            "saint charles, mn": ['Rochester'],
            "san dimas, ca": ['Inland Empire'],
            "san gabriel, ca": ['Inland Empire'],
            "san pablo, ca": ['Bay Area'],
            "san ramon, ca": ['Bay Area'],
            "sanatoga, pa": ['Trenton'],
            "santa clara, ca": ['Inland Empire'],
            "santa cruz, ca": ['Inland Empire'],
            "saratoga, ca": ['Bay Area'],
            "sargeant, mn": ['Rochester'],
            "satsuma, tx": ['Houston'],
            "schley, ia": ['Des Moines'],
            "scottsdale trailer corral, az": ['Phoenix'],
            "seagoville, tx": ['Dallas'],
            "sealy, tx": ['Houston'],
            "searsboro, ia": ['Des Moines'],
            "sebastopol, ca": ['Bay Area'],
            "sedalia, co": ['Denver'],
            "sellersville, pa": ['Trenton'],
            "shakopee, mn": ['Rochester'],
            "sheridan, co": ['Denver'],
            "sienna, tx": ['Houston'],
            "skippack, pa": ['Trenton'],
            "slatington, pa": ['Trenton'],
            "sleepy hollow, ca": ['Bay Area'],
            "sonoma, ca": ['Bay Area'],
            "south el monte, ca": ['Inland Empire'],
            "south gate, ca": ['Inland Empire'],
            "south pasadena, ca": ['Inland Empire'],
            "south st paul, mn": ['Rochester'],
            "southside place, tx": ['Houston'],
            "springfield gardens, ny": ['Newark'],
            "st paul park, mn": ['Rochester'],
            "st paul, mn": ['Rochester'],
            "stacyville, ia": ['Des Moines'],
            "stevinson, ca": ['Sacramento'],
            "story city, ia": ['Des Moines'],
            "succasunna, nj": ['Newark'],
            "summerlin south, nv": ['Las Vegas'],
            "summit, mn": ['Rochester'],
            "sun lakes, az": ['Phoenix'],
            "sunnyside gardens, ny": ['Newark'],
            "superior, co": ['Denver'],
            "suprstitn mtn, az": ['Phoenix'],
            "sussex, nj": ['Newark'],
            "swarthmore, pa": ['Trenton'],
            "sweet water village, az": ['Phoenix'],
            "taft mosswood, ca": ['Sacramento'],
            "taopi, mn": ['Rochester'],
            "tara hills, ca": ['Bay Area'],
            "telford, pa": ['Trenton'],
            "terrell, tx": ['Dallas'],
            "toeterville, ia": ['Des Moines'],
            "tonopah, az": ['Phoenix'],
            "totowa, nj": ['Newark'],
            "tullytown, pa": ['Trenton'],
            "tustin, ca": ['Inland Empire'],
            "university park, tx": ['Dallas'],
            "upper darby, pa": ['Trenton'],
            "utica, mn": ['Rochester'],
            "vallejo, ca": ['Bay Area'],
            "venus, tx": ['Dallas'],
            "vermillion, mn": ['Rochester'],
            "villanova, pa": ['Trenton'],
            "walnut grove, ca": ['Bay Area'],
            "walnut, ca": ['Inland Empire'],
            "waltham, mn": ['Rochester'],
            "wanamingo, mn": ['Rochester'],
            "wantagh, ny": ['Newark'],
            "warminster, pa": ['Trenton'],
            "warsaw, mn": ['Rochester'],
            "waterford, ca": ['Sacramento'],
            "watkins, co": ['Denver'],
            "wattenberg, co": ['Denver'],
            "webb, tx": ['Dallas'],
            "webster, tx": ['Houston'],
            "welch, mn": ['Rochester'],
            "wescosville, pa": ['Trenton'],
            "west easton, pa": ['Trenton'],
            "west modesto, ca": ['Inland Empire'],
            "west norriton, pa": ['Trenton'],
            "westbury, ny": ['Newark'],
            "westminster, ca": ['Inland Empire'],
            "wheat ridge, co": ['Denver'],
            "wheatland, ca": ['Sacramento'],
            "whippany, nj": ['Newark'],
            "white rock, mn": ['Rochester'],
            "whitehall township, pa": ['Trenton'],
            "whitestone, ny": ['Newark'],
            "whittier, ca": ['Inland Empire'],
            "willis, tx": ['Houston'],
            "willow grove, pa": ['Trenton'],
            "wilson, ca": ['Sacramento'],
            "wilton, ca": ['Inland Empire'],
            "windsor, co": ['Denver'],
            "winter park, co": ['Denver'],
            "winters, ca": ['Sacramento'],
            "wittmann, az": ['Phoenix'],
            "woodbranch, tx": ['Houston'],
            "woodmoor, co": ['Denver'],
            "wrightwood, ca": ['Inland Empire'],
            "wykoff, mn": ['Rochester'],
            "yeadon, pa": ['Trenton'],
            "yorba linda, ca": ['Inland Empire'],
            "yucaipa, ca": ['Inland Empire'],
            "yucca valley, ca": ['Inland Empire'],
            "zumbro falls, mn": ['Rochester'],
}
    
    def map_market(self, location_string):
        """Map a location string to its primary market"""
        if not isinstance(location_string, str):
            return ""
        location_string = location_string.lower().strip()
        return self.market_lookup.get(location_string, [""])[0]
    
    def map_markets(self, df):
        """Map markets for a DataFrame of jobs"""
        import pandas as pd
        if not isinstance(df, pd.DataFrame):
            return df
        
        # Add market column by mapping each location
        df['market'] = df['location'].apply(self.map_market)
        return df
    
    def get_all_markets(self):
        """Get a list of all unique markets"""
        all_markets = set()
        for markets in self.market_lookup.values():
            all_markets.update(markets)
        return sorted(list(all_markets))
    
    def get_cities_in_market(self, market_name):
        """Get all cities mapped to a specific market"""
        cities = []
        for city, markets in self.market_lookup.items():
            if market_name in markets:
                cities.append(city)
        return sorted(cities)
    
    def search_markets(self, search_term):
        """Search for markets containing the search term"""
        search_term = search_term.lower()
        matching_markets = []
        for market in self.get_all_markets():
            if search_term in market.lower():
                matching_markets.append(market)
        return sorted(matching_markets)

if __name__ == "__main__":
    # Test the market mapper
    mapper = MarketMapper()
    
    test_locations = [
        "Dallas, TX",
        "houston, tx", 
        "Phoenix, AZ",
        "Unknown City, CA"
    ]
    
    print("Market mapping test:")
    for location in test_locations:
        market = mapper.map_market(location)
        print(f"  '{location}' → '{market}'")
    
    print(f"\nTotal markets available: {len(mapper.get_all_markets())}")
    print(f"First 10 markets: {mapper.get_all_markets()[:10]}")
    
    print(f"\nCities in Dallas market: {len(mapper.get_cities_in_market('Dallas'))}")
    print(f"First 5 Dallas cities: {mapper.get_cities_in_market('Dallas')[:5]}")