# Minimal secrets for local testing - portal parameter encoding test
[secrets]
# Dummy values for local testing
OPENAI_API_KEY = "dummy-key-for-testing"
SUPABASE_URL = "https://dummy.supabase.co"
SUPABASE_ANON_KEY = "dummy-anon-key"
AIRTABLE_API_KEY = "dummy-airtable-key"
AIRTABLE_BASE_ID = "dummy-base-id"
AIRTABLE_TABLE_ID = "dummy-table-id"
OUTSCRAPER_API_KEY = "dummy-outscraper-key"
SHORT_IO_API_KEY = "dummy-shortio-key"
APP_PASSWORD = "freeworld2024"